// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------- //
// LED_MUX //
// ------- //

#define LED_MUX_wrap_target 0
#define LED_MUX_wrap 13

static const uint16_t LED_MUX_program_instructions[] = {
            //     .wrap_target
    0xe040, //  0: set    y, 0                       
    0xa0e2, //  1: mov    osr, y                     
    0x7f10, //  2: out    pins, 16               [31]
    0x80a0, //  3: pull   block                      
    0xbf25, //  4: mov    x, status              [31]
    0x0027, //  5: jmp    !x, 7                      
    0xc000, //  6: irq    nowait 0                   
    0x7f10, //  7: out    pins, 16               [31]
    0xa027, //  8: mov    x, osr                     
    0xe040, //  9: set    y, 0                       
    0xa0e2, // 10: mov    osr, y                     
    0x7f10, // 11: out    pins, 16               [31]
    0xbfe1, // 12: mov    osr, x                 [31]
    0x7f10, // 13: out    pins, 16               [31]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program LED_MUX_program = {
    .instructions = LED_MUX_program_instructions,
    .length = 14,
    .origin = -1,
};

static inline pio_sm_config LED_MUX_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + LED_MUX_wrap_target, offset + LED_MUX_wrap);
    return c;
}
#endif
